// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package rule_group

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/networkfirewall"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/networkfirewall/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/networkfirewall-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.RuleGroup{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.DescribeRuleGroupOutput
	resp, err = rm.sdkapi.DescribeRuleGroup(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "DescribeRuleGroup", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.RuleGroup != nil {
		f0 := &svcapitypes.RuleGroup_SDK{}
		if resp.RuleGroup.ReferenceSets != nil {
			f0f0 := &svcapitypes.ReferenceSets{}
			if resp.RuleGroup.ReferenceSets.IPSetReferences != nil {
				f0f0f0 := map[string]*svcapitypes.IPSetReference{}
				for f0f0f0key, f0f0f0valiter := range resp.RuleGroup.ReferenceSets.IPSetReferences {
					f0f0f0val := &svcapitypes.IPSetReference{}
					if f0f0f0valiter.ReferenceArn != nil {
						f0f0f0val.ReferenceARN = f0f0f0valiter.ReferenceArn
					}
					f0f0f0[f0f0f0key] = f0f0f0val
				}
				f0f0.IPSetReferences = f0f0f0
			}
			f0.ReferenceSets = f0f0
		}
		if resp.RuleGroup.RuleVariables != nil {
			f0f1 := &svcapitypes.RuleVariables{}
			if resp.RuleGroup.RuleVariables.IPSets != nil {
				f0f1f0 := map[string]*svcapitypes.IPSet{}
				for f0f1f0key, f0f1f0valiter := range resp.RuleGroup.RuleVariables.IPSets {
					f0f1f0val := &svcapitypes.IPSet{}
					if f0f1f0valiter.Definition != nil {
						f0f1f0val.Definition = aws.StringSlice(f0f1f0valiter.Definition)
					}
					f0f1f0[f0f1f0key] = f0f1f0val
				}
				f0f1.IPSets = f0f1f0
			}
			if resp.RuleGroup.RuleVariables.PortSets != nil {
				f0f1f1 := map[string]*svcapitypes.PortSet{}
				for f0f1f1key, f0f1f1valiter := range resp.RuleGroup.RuleVariables.PortSets {
					f0f1f1val := &svcapitypes.PortSet{}
					if f0f1f1valiter.Definition != nil {
						f0f1f1val.Definition = aws.StringSlice(f0f1f1valiter.Definition)
					}
					f0f1f1[f0f1f1key] = f0f1f1val
				}
				f0f1.PortSets = f0f1f1
			}
			f0.RuleVariables = f0f1
		}
		if resp.RuleGroup.RulesSource != nil {
			f0f2 := &svcapitypes.RulesSource{}
			if resp.RuleGroup.RulesSource.RulesSourceList != nil {
				f0f2f0 := &svcapitypes.RulesSourceList{}
				if resp.RuleGroup.RulesSource.RulesSourceList.GeneratedRulesType != "" {
					f0f2f0.GeneratedRulesType = aws.String(string(resp.RuleGroup.RulesSource.RulesSourceList.GeneratedRulesType))
				}
				if resp.RuleGroup.RulesSource.RulesSourceList.TargetTypes != nil {
					f0f2f0f1 := []*string{}
					for _, f0f2f0f1iter := range resp.RuleGroup.RulesSource.RulesSourceList.TargetTypes {
						var f0f2f0f1elem *string
						f0f2f0f1elem = aws.String(string(f0f2f0f1iter))
						f0f2f0f1 = append(f0f2f0f1, f0f2f0f1elem)
					}
					f0f2f0.TargetTypes = f0f2f0f1
				}
				if resp.RuleGroup.RulesSource.RulesSourceList.Targets != nil {
					f0f2f0.Targets = aws.StringSlice(resp.RuleGroup.RulesSource.RulesSourceList.Targets)
				}
				f0f2.RulesSourceList = f0f2f0
			}
			if resp.RuleGroup.RulesSource.RulesString != nil {
				f0f2.RulesString = resp.RuleGroup.RulesSource.RulesString
			}
			if resp.RuleGroup.RulesSource.StatefulRules != nil {
				f0f2f2 := []*svcapitypes.StatefulRule{}
				for _, f0f2f2iter := range resp.RuleGroup.RulesSource.StatefulRules {
					f0f2f2elem := &svcapitypes.StatefulRule{}
					if f0f2f2iter.Action != "" {
						f0f2f2elem.Action = aws.String(string(f0f2f2iter.Action))
					}
					if f0f2f2iter.Header != nil {
						f0f2f2elemf1 := &svcapitypes.Header{}
						if f0f2f2iter.Header.Destination != nil {
							f0f2f2elemf1.Destination = f0f2f2iter.Header.Destination
						}
						if f0f2f2iter.Header.DestinationPort != nil {
							f0f2f2elemf1.DestinationPort = f0f2f2iter.Header.DestinationPort
						}
						if f0f2f2iter.Header.Direction != "" {
							f0f2f2elemf1.Direction = aws.String(string(f0f2f2iter.Header.Direction))
						}
						if f0f2f2iter.Header.Protocol != "" {
							f0f2f2elemf1.Protocol = aws.String(string(f0f2f2iter.Header.Protocol))
						}
						if f0f2f2iter.Header.Source != nil {
							f0f2f2elemf1.Source = f0f2f2iter.Header.Source
						}
						if f0f2f2iter.Header.SourcePort != nil {
							f0f2f2elemf1.SourcePort = f0f2f2iter.Header.SourcePort
						}
						f0f2f2elem.Header = f0f2f2elemf1
					}
					if f0f2f2iter.RuleOptions != nil {
						f0f2f2elemf2 := []*svcapitypes.RuleOption{}
						for _, f0f2f2elemf2iter := range f0f2f2iter.RuleOptions {
							f0f2f2elemf2elem := &svcapitypes.RuleOption{}
							if f0f2f2elemf2iter.Keyword != nil {
								f0f2f2elemf2elem.Keyword = f0f2f2elemf2iter.Keyword
							}
							if f0f2f2elemf2iter.Settings != nil {
								f0f2f2elemf2elem.Settings = aws.StringSlice(f0f2f2elemf2iter.Settings)
							}
							f0f2f2elemf2 = append(f0f2f2elemf2, f0f2f2elemf2elem)
						}
						f0f2f2elem.RuleOptions = f0f2f2elemf2
					}
					f0f2f2 = append(f0f2f2, f0f2f2elem)
				}
				f0f2.StatefulRules = f0f2f2
			}
			if resp.RuleGroup.RulesSource.StatelessRulesAndCustomActions != nil {
				f0f2f3 := &svcapitypes.StatelessRulesAndCustomActions{}
				if resp.RuleGroup.RulesSource.StatelessRulesAndCustomActions.CustomActions != nil {
					f0f2f3f0 := []*svcapitypes.CustomAction{}
					for _, f0f2f3f0iter := range resp.RuleGroup.RulesSource.StatelessRulesAndCustomActions.CustomActions {
						f0f2f3f0elem := &svcapitypes.CustomAction{}
						if f0f2f3f0iter.ActionDefinition != nil {
							f0f2f3f0elemf0 := &svcapitypes.ActionDefinition{}
							if f0f2f3f0iter.ActionDefinition.PublishMetricAction != nil {
								f0f2f3f0elemf0f0 := &svcapitypes.PublishMetricAction{}
								if f0f2f3f0iter.ActionDefinition.PublishMetricAction.Dimensions != nil {
									f0f2f3f0elemf0f0f0 := []*svcapitypes.Dimension{}
									for _, f0f2f3f0elemf0f0f0iter := range f0f2f3f0iter.ActionDefinition.PublishMetricAction.Dimensions {
										f0f2f3f0elemf0f0f0elem := &svcapitypes.Dimension{}
										if f0f2f3f0elemf0f0f0iter.Value != nil {
											f0f2f3f0elemf0f0f0elem.Value = f0f2f3f0elemf0f0f0iter.Value
										}
										f0f2f3f0elemf0f0f0 = append(f0f2f3f0elemf0f0f0, f0f2f3f0elemf0f0f0elem)
									}
									f0f2f3f0elemf0f0.Dimensions = f0f2f3f0elemf0f0f0
								}
								f0f2f3f0elemf0.PublishMetricAction = f0f2f3f0elemf0f0
							}
							f0f2f3f0elem.ActionDefinition = f0f2f3f0elemf0
						}
						if f0f2f3f0iter.ActionName != nil {
							f0f2f3f0elem.ActionName = f0f2f3f0iter.ActionName
						}
						f0f2f3f0 = append(f0f2f3f0, f0f2f3f0elem)
					}
					f0f2f3.CustomActions = f0f2f3f0
				}
				if resp.RuleGroup.RulesSource.StatelessRulesAndCustomActions.StatelessRules != nil {
					f0f2f3f1 := []*svcapitypes.StatelessRule{}
					for _, f0f2f3f1iter := range resp.RuleGroup.RulesSource.StatelessRulesAndCustomActions.StatelessRules {
						f0f2f3f1elem := &svcapitypes.StatelessRule{}
						if f0f2f3f1iter.Priority != nil {
							priorityCopy := int64(*f0f2f3f1iter.Priority)
							f0f2f3f1elem.Priority = &priorityCopy
						}
						if f0f2f3f1iter.RuleDefinition != nil {
							f0f2f3f1elemf1 := &svcapitypes.RuleDefinition{}
							if f0f2f3f1iter.RuleDefinition.Actions != nil {
								f0f2f3f1elemf1.Actions = aws.StringSlice(f0f2f3f1iter.RuleDefinition.Actions)
							}
							if f0f2f3f1iter.RuleDefinition.MatchAttributes != nil {
								f0f2f3f1elemf1f1 := &svcapitypes.MatchAttributes{}
								if f0f2f3f1iter.RuleDefinition.MatchAttributes.DestinationPorts != nil {
									f0f2f3f1elemf1f1f0 := []*svcapitypes.PortRange{}
									for _, f0f2f3f1elemf1f1f0iter := range f0f2f3f1iter.RuleDefinition.MatchAttributes.DestinationPorts {
										f0f2f3f1elemf1f1f0elem := &svcapitypes.PortRange{}
										fromPortCopy := int64(f0f2f3f1elemf1f1f0iter.FromPort)
										f0f2f3f1elemf1f1f0elem.FromPort = &fromPortCopy
										toPortCopy := int64(f0f2f3f1elemf1f1f0iter.ToPort)
										f0f2f3f1elemf1f1f0elem.ToPort = &toPortCopy
										f0f2f3f1elemf1f1f0 = append(f0f2f3f1elemf1f1f0, f0f2f3f1elemf1f1f0elem)
									}
									f0f2f3f1elemf1f1.DestinationPorts = f0f2f3f1elemf1f1f0
								}
								if f0f2f3f1iter.RuleDefinition.MatchAttributes.Destinations != nil {
									f0f2f3f1elemf1f1f1 := []*svcapitypes.Address{}
									for _, f0f2f3f1elemf1f1f1iter := range f0f2f3f1iter.RuleDefinition.MatchAttributes.Destinations {
										f0f2f3f1elemf1f1f1elem := &svcapitypes.Address{}
										if f0f2f3f1elemf1f1f1iter.AddressDefinition != nil {
											f0f2f3f1elemf1f1f1elem.AddressDefinition = f0f2f3f1elemf1f1f1iter.AddressDefinition
										}
										f0f2f3f1elemf1f1f1 = append(f0f2f3f1elemf1f1f1, f0f2f3f1elemf1f1f1elem)
									}
									f0f2f3f1elemf1f1.Destinations = f0f2f3f1elemf1f1f1
								}
								if f0f2f3f1iter.RuleDefinition.MatchAttributes.Protocols != nil {
									f0f2f3f1elemf1f1f2 := []*int64{}
									for _, f0f2f3f1elemf1f1f2iter := range f0f2f3f1iter.RuleDefinition.MatchAttributes.Protocols {
										var f0f2f3f1elemf1f1f2elem *int64
										protocolNumberCopy := int64(f0f2f3f1elemf1f1f2iter)
										f0f2f3f1elemf1f1f2elem = &protocolNumberCopy
										f0f2f3f1elemf1f1f2 = append(f0f2f3f1elemf1f1f2, f0f2f3f1elemf1f1f2elem)
									}
									f0f2f3f1elemf1f1.Protocols = f0f2f3f1elemf1f1f2
								}
								if f0f2f3f1iter.RuleDefinition.MatchAttributes.SourcePorts != nil {
									f0f2f3f1elemf1f1f3 := []*svcapitypes.PortRange{}
									for _, f0f2f3f1elemf1f1f3iter := range f0f2f3f1iter.RuleDefinition.MatchAttributes.SourcePorts {
										f0f2f3f1elemf1f1f3elem := &svcapitypes.PortRange{}
										fromPortCopy := int64(f0f2f3f1elemf1f1f3iter.FromPort)
										f0f2f3f1elemf1f1f3elem.FromPort = &fromPortCopy
										toPortCopy := int64(f0f2f3f1elemf1f1f3iter.ToPort)
										f0f2f3f1elemf1f1f3elem.ToPort = &toPortCopy
										f0f2f3f1elemf1f1f3 = append(f0f2f3f1elemf1f1f3, f0f2f3f1elemf1f1f3elem)
									}
									f0f2f3f1elemf1f1.SourcePorts = f0f2f3f1elemf1f1f3
								}
								if f0f2f3f1iter.RuleDefinition.MatchAttributes.Sources != nil {
									f0f2f3f1elemf1f1f4 := []*svcapitypes.Address{}
									for _, f0f2f3f1elemf1f1f4iter := range f0f2f3f1iter.RuleDefinition.MatchAttributes.Sources {
										f0f2f3f1elemf1f1f4elem := &svcapitypes.Address{}
										if f0f2f3f1elemf1f1f4iter.AddressDefinition != nil {
											f0f2f3f1elemf1f1f4elem.AddressDefinition = f0f2f3f1elemf1f1f4iter.AddressDefinition
										}
										f0f2f3f1elemf1f1f4 = append(f0f2f3f1elemf1f1f4, f0f2f3f1elemf1f1f4elem)
									}
									f0f2f3f1elemf1f1.Sources = f0f2f3f1elemf1f1f4
								}
								if f0f2f3f1iter.RuleDefinition.MatchAttributes.TCPFlags != nil {
									f0f2f3f1elemf1f1f5 := []*svcapitypes.TCPFlagField{}
									for _, f0f2f3f1elemf1f1f5iter := range f0f2f3f1iter.RuleDefinition.MatchAttributes.TCPFlags {
										f0f2f3f1elemf1f1f5elem := &svcapitypes.TCPFlagField{}
										if f0f2f3f1elemf1f1f5iter.Flags != nil {
											f0f2f3f1elemf1f1f5elemf0 := []*string{}
											for _, f0f2f3f1elemf1f1f5elemf0iter := range f0f2f3f1elemf1f1f5iter.Flags {
												var f0f2f3f1elemf1f1f5elemf0elem *string
												f0f2f3f1elemf1f1f5elemf0elem = aws.String(string(f0f2f3f1elemf1f1f5elemf0iter))
												f0f2f3f1elemf1f1f5elemf0 = append(f0f2f3f1elemf1f1f5elemf0, f0f2f3f1elemf1f1f5elemf0elem)
											}
											f0f2f3f1elemf1f1f5elem.Flags = f0f2f3f1elemf1f1f5elemf0
										}
										if f0f2f3f1elemf1f1f5iter.Masks != nil {
											f0f2f3f1elemf1f1f5elemf1 := []*string{}
											for _, f0f2f3f1elemf1f1f5elemf1iter := range f0f2f3f1elemf1f1f5iter.Masks {
												var f0f2f3f1elemf1f1f5elemf1elem *string
												f0f2f3f1elemf1f1f5elemf1elem = aws.String(string(f0f2f3f1elemf1f1f5elemf1iter))
												f0f2f3f1elemf1f1f5elemf1 = append(f0f2f3f1elemf1f1f5elemf1, f0f2f3f1elemf1f1f5elemf1elem)
											}
											f0f2f3f1elemf1f1f5elem.Masks = f0f2f3f1elemf1f1f5elemf1
										}
										f0f2f3f1elemf1f1f5 = append(f0f2f3f1elemf1f1f5, f0f2f3f1elemf1f1f5elem)
									}
									f0f2f3f1elemf1f1.TCPFlags = f0f2f3f1elemf1f1f5
								}
								f0f2f3f1elemf1.MatchAttributes = f0f2f3f1elemf1f1
							}
							f0f2f3f1elem.RuleDefinition = f0f2f3f1elemf1
						}
						f0f2f3f1 = append(f0f2f3f1, f0f2f3f1elem)
					}
					f0f2f3.StatelessRules = f0f2f3f1
				}
				f0f2.StatelessRulesAndCustomActions = f0f2f3
			}
			f0.RulesSource = f0f2
		}
		if resp.RuleGroup.StatefulRuleOptions != nil {
			f0f3 := &svcapitypes.StatefulRuleOptions{}
			if resp.RuleGroup.StatefulRuleOptions.RuleOrder != "" {
				f0f3.RuleOrder = aws.String(string(resp.RuleGroup.StatefulRuleOptions.RuleOrder))
			}
			f0.StatefulRuleOptions = f0f3
		}
		ko.Spec.RuleGroup = f0
	} else {
		ko.Spec.RuleGroup = nil
	}
	if resp.RuleGroupResponse != nil {
		f1 := &svcapitypes.RuleGroupResponse{}
		if resp.RuleGroupResponse.AnalysisResults != nil {
			f1f0 := []*svcapitypes.AnalysisResult{}
			for _, f1f0iter := range resp.RuleGroupResponse.AnalysisResults {
				f1f0elem := &svcapitypes.AnalysisResult{}
				if f1f0iter.AnalysisDetail != nil {
					f1f0elem.AnalysisDetail = f1f0iter.AnalysisDetail
				}
				if f1f0iter.IdentifiedRuleIds != nil {
					f1f0elem.IDentifiedRuleIDs = aws.StringSlice(f1f0iter.IdentifiedRuleIds)
				}
				if f1f0iter.IdentifiedType != "" {
					f1f0elem.IDentifiedType = aws.String(string(f1f0iter.IdentifiedType))
				}
				f1f0 = append(f1f0, f1f0elem)
			}
			f1.AnalysisResults = f1f0
		}
		if resp.RuleGroupResponse.Capacity != nil {
			capacityCopy := int64(*resp.RuleGroupResponse.Capacity)
			f1.Capacity = &capacityCopy
		}
		if resp.RuleGroupResponse.ConsumedCapacity != nil {
			consumedCapacityCopy := int64(*resp.RuleGroupResponse.ConsumedCapacity)
			f1.ConsumedCapacity = &consumedCapacityCopy
		}
		if resp.RuleGroupResponse.Description != nil {
			f1.Description = resp.RuleGroupResponse.Description
		}
		if resp.RuleGroupResponse.EncryptionConfiguration != nil {
			f1f4 := &svcapitypes.EncryptionConfiguration{}
			if resp.RuleGroupResponse.EncryptionConfiguration.KeyId != nil {
				f1f4.KeyID = resp.RuleGroupResponse.EncryptionConfiguration.KeyId
			}
			if resp.RuleGroupResponse.EncryptionConfiguration.Type != "" {
				f1f4.Type = aws.String(string(resp.RuleGroupResponse.EncryptionConfiguration.Type))
			}
			f1.EncryptionConfiguration = f1f4
		}
		if resp.RuleGroupResponse.LastModifiedTime != nil {
			f1.LastModifiedTime = &metav1.Time{*resp.RuleGroupResponse.LastModifiedTime}
		}
		if resp.RuleGroupResponse.NumberOfAssociations != nil {
			numberOfAssociationsCopy := int64(*resp.RuleGroupResponse.NumberOfAssociations)
			f1.NumberOfAssociations = &numberOfAssociationsCopy
		}
		if resp.RuleGroupResponse.RuleGroupArn != nil {
			f1.RuleGroupARN = resp.RuleGroupResponse.RuleGroupArn
		}
		if resp.RuleGroupResponse.RuleGroupId != nil {
			f1.RuleGroupID = resp.RuleGroupResponse.RuleGroupId
		}
		if resp.RuleGroupResponse.RuleGroupName != nil {
			f1.RuleGroupName = resp.RuleGroupResponse.RuleGroupName
		}
		if resp.RuleGroupResponse.RuleGroupStatus != "" {
			f1.RuleGroupStatus = aws.String(string(resp.RuleGroupResponse.RuleGroupStatus))
		}
		if resp.RuleGroupResponse.SnsTopic != nil {
			f1.SNSTopic = resp.RuleGroupResponse.SnsTopic
		}
		if resp.RuleGroupResponse.SourceMetadata != nil {
			f1f12 := &svcapitypes.SourceMetadata{}
			if resp.RuleGroupResponse.SourceMetadata.SourceArn != nil {
				f1f12.SourceARN = resp.RuleGroupResponse.SourceMetadata.SourceArn
			}
			if resp.RuleGroupResponse.SourceMetadata.SourceUpdateToken != nil {
				f1f12.SourceUpdateToken = resp.RuleGroupResponse.SourceMetadata.SourceUpdateToken
			}
			f1.SourceMetadata = f1f12
		}
		if resp.RuleGroupResponse.Tags != nil {
			f1f13 := []*svcapitypes.Tag{}
			for _, f1f13iter := range resp.RuleGroupResponse.Tags {
				f1f13elem := &svcapitypes.Tag{}
				if f1f13iter.Key != nil {
					f1f13elem.Key = f1f13iter.Key
				}
				if f1f13iter.Value != nil {
					f1f13elem.Value = f1f13iter.Value
				}
				f1f13 = append(f1f13, f1f13elem)
			}
			f1.Tags = f1f13
		}
		if resp.RuleGroupResponse.Type != "" {
			f1.Type = aws.String(string(resp.RuleGroupResponse.Type))
		}
		ko.Status.RuleGroupResponse = f1
	} else {
		ko.Status.RuleGroupResponse = nil
	}
	if resp.UpdateToken != nil {
		ko.Status.UpdateToken = resp.UpdateToken
	} else {
		ko.Status.UpdateToken = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return false
}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeRuleGroupInput, error) {
	res := &svcsdk.DescribeRuleGroupInput{}

	if r.ko.Spec.AnalyzeRuleGroup != nil {
		res.AnalyzeRuleGroup = *r.ko.Spec.AnalyzeRuleGroup
	}
	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.RuleGroupArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}
	if r.ko.Spec.RuleGroupName != nil {
		res.RuleGroupName = r.ko.Spec.RuleGroupName
	}
	if r.ko.Spec.Type != nil {
		res.Type = svcsdktypes.RuleGroupType(*r.ko.Spec.Type)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateRuleGroupOutput
	_ = resp
	resp, err = rm.sdkapi.CreateRuleGroup(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateRuleGroup", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.RuleGroupResponse != nil {
		f0 := &svcapitypes.RuleGroupResponse{}
		if resp.RuleGroupResponse.AnalysisResults != nil {
			f0f0 := []*svcapitypes.AnalysisResult{}
			for _, f0f0iter := range resp.RuleGroupResponse.AnalysisResults {
				f0f0elem := &svcapitypes.AnalysisResult{}
				if f0f0iter.AnalysisDetail != nil {
					f0f0elem.AnalysisDetail = f0f0iter.AnalysisDetail
				}
				if f0f0iter.IdentifiedRuleIds != nil {
					f0f0elem.IDentifiedRuleIDs = aws.StringSlice(f0f0iter.IdentifiedRuleIds)
				}
				if f0f0iter.IdentifiedType != "" {
					f0f0elem.IDentifiedType = aws.String(string(f0f0iter.IdentifiedType))
				}
				f0f0 = append(f0f0, f0f0elem)
			}
			f0.AnalysisResults = f0f0
		}
		if resp.RuleGroupResponse.Capacity != nil {
			capacityCopy := int64(*resp.RuleGroupResponse.Capacity)
			f0.Capacity = &capacityCopy
		}
		if resp.RuleGroupResponse.ConsumedCapacity != nil {
			consumedCapacityCopy := int64(*resp.RuleGroupResponse.ConsumedCapacity)
			f0.ConsumedCapacity = &consumedCapacityCopy
		}
		if resp.RuleGroupResponse.Description != nil {
			f0.Description = resp.RuleGroupResponse.Description
		}
		if resp.RuleGroupResponse.EncryptionConfiguration != nil {
			f0f4 := &svcapitypes.EncryptionConfiguration{}
			if resp.RuleGroupResponse.EncryptionConfiguration.KeyId != nil {
				f0f4.KeyID = resp.RuleGroupResponse.EncryptionConfiguration.KeyId
			}
			if resp.RuleGroupResponse.EncryptionConfiguration.Type != "" {
				f0f4.Type = aws.String(string(resp.RuleGroupResponse.EncryptionConfiguration.Type))
			}
			f0.EncryptionConfiguration = f0f4
		}
		if resp.RuleGroupResponse.LastModifiedTime != nil {
			f0.LastModifiedTime = &metav1.Time{*resp.RuleGroupResponse.LastModifiedTime}
		}
		if resp.RuleGroupResponse.NumberOfAssociations != nil {
			numberOfAssociationsCopy := int64(*resp.RuleGroupResponse.NumberOfAssociations)
			f0.NumberOfAssociations = &numberOfAssociationsCopy
		}
		if resp.RuleGroupResponse.RuleGroupArn != nil {
			f0.RuleGroupARN = resp.RuleGroupResponse.RuleGroupArn
		}
		if resp.RuleGroupResponse.RuleGroupId != nil {
			f0.RuleGroupID = resp.RuleGroupResponse.RuleGroupId
		}
		if resp.RuleGroupResponse.RuleGroupName != nil {
			f0.RuleGroupName = resp.RuleGroupResponse.RuleGroupName
		}
		if resp.RuleGroupResponse.RuleGroupStatus != "" {
			f0.RuleGroupStatus = aws.String(string(resp.RuleGroupResponse.RuleGroupStatus))
		}
		if resp.RuleGroupResponse.SnsTopic != nil {
			f0.SNSTopic = resp.RuleGroupResponse.SnsTopic
		}
		if resp.RuleGroupResponse.SourceMetadata != nil {
			f0f12 := &svcapitypes.SourceMetadata{}
			if resp.RuleGroupResponse.SourceMetadata.SourceArn != nil {
				f0f12.SourceARN = resp.RuleGroupResponse.SourceMetadata.SourceArn
			}
			if resp.RuleGroupResponse.SourceMetadata.SourceUpdateToken != nil {
				f0f12.SourceUpdateToken = resp.RuleGroupResponse.SourceMetadata.SourceUpdateToken
			}
			f0.SourceMetadata = f0f12
		}
		if resp.RuleGroupResponse.Tags != nil {
			f0f13 := []*svcapitypes.Tag{}
			for _, f0f13iter := range resp.RuleGroupResponse.Tags {
				f0f13elem := &svcapitypes.Tag{}
				if f0f13iter.Key != nil {
					f0f13elem.Key = f0f13iter.Key
				}
				if f0f13iter.Value != nil {
					f0f13elem.Value = f0f13iter.Value
				}
				f0f13 = append(f0f13, f0f13elem)
			}
			f0.Tags = f0f13
		}
		if resp.RuleGroupResponse.Type != "" {
			f0.Type = aws.String(string(resp.RuleGroupResponse.Type))
		}
		ko.Status.RuleGroupResponse = f0
	} else {
		ko.Status.RuleGroupResponse = nil
	}
	if resp.UpdateToken != nil {
		ko.Status.UpdateToken = resp.UpdateToken
	} else {
		ko.Status.UpdateToken = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateRuleGroupInput, error) {
	res := &svcsdk.CreateRuleGroupInput{}

	if r.ko.Spec.AnalyzeRuleGroup != nil {
		res.AnalyzeRuleGroup = *r.ko.Spec.AnalyzeRuleGroup
	}
	if r.ko.Spec.Capacity != nil {
		capacityCopy0 := *r.ko.Spec.Capacity
		if capacityCopy0 > math.MaxInt32 || capacityCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field Capacity is of type int32")
		}
		capacityCopy := int32(capacityCopy0)
		res.Capacity = &capacityCopy
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.DryRun != nil {
		res.DryRun = *r.ko.Spec.DryRun
	}
	if r.ko.Spec.EncryptionConfiguration != nil {
		f4 := &svcsdktypes.EncryptionConfiguration{}
		if r.ko.Spec.EncryptionConfiguration.KeyID != nil {
			f4.KeyId = r.ko.Spec.EncryptionConfiguration.KeyID
		}
		if r.ko.Spec.EncryptionConfiguration.Type != nil {
			f4.Type = svcsdktypes.EncryptionType(*r.ko.Spec.EncryptionConfiguration.Type)
		}
		res.EncryptionConfiguration = f4
	}
	if r.ko.Spec.RuleGroup != nil {
		f5 := &svcsdktypes.RuleGroup{}
		if r.ko.Spec.RuleGroup.ReferenceSets != nil {
			f5f0 := &svcsdktypes.ReferenceSets{}
			if r.ko.Spec.RuleGroup.ReferenceSets.IPSetReferences != nil {
				f5f0f0 := map[string]svcsdktypes.IPSetReference{}
				for f5f0f0key, f5f0f0valiter := range r.ko.Spec.RuleGroup.ReferenceSets.IPSetReferences {
					f5f0f0val := &svcsdktypes.IPSetReference{}
					if f5f0f0valiter.ReferenceARN != nil {
						f5f0f0val.ReferenceArn = f5f0f0valiter.ReferenceARN
					}
					f5f0f0[f5f0f0key] = *f5f0f0val
				}
				f5f0.IPSetReferences = f5f0f0
			}
			f5.ReferenceSets = f5f0
		}
		if r.ko.Spec.RuleGroup.RuleVariables != nil {
			f5f1 := &svcsdktypes.RuleVariables{}
			if r.ko.Spec.RuleGroup.RuleVariables.IPSets != nil {
				f5f1f0 := map[string]svcsdktypes.IPSet{}
				for f5f1f0key, f5f1f0valiter := range r.ko.Spec.RuleGroup.RuleVariables.IPSets {
					f5f1f0val := &svcsdktypes.IPSet{}
					if f5f1f0valiter.Definition != nil {
						f5f1f0val.Definition = aws.ToStringSlice(f5f1f0valiter.Definition)
					}
					f5f1f0[f5f1f0key] = *f5f1f0val
				}
				f5f1.IPSets = f5f1f0
			}
			if r.ko.Spec.RuleGroup.RuleVariables.PortSets != nil {
				f5f1f1 := map[string]svcsdktypes.PortSet{}
				for f5f1f1key, f5f1f1valiter := range r.ko.Spec.RuleGroup.RuleVariables.PortSets {
					f5f1f1val := &svcsdktypes.PortSet{}
					if f5f1f1valiter.Definition != nil {
						f5f1f1val.Definition = aws.ToStringSlice(f5f1f1valiter.Definition)
					}
					f5f1f1[f5f1f1key] = *f5f1f1val
				}
				f5f1.PortSets = f5f1f1
			}
			f5.RuleVariables = f5f1
		}
		if r.ko.Spec.RuleGroup.RulesSource != nil {
			f5f2 := &svcsdktypes.RulesSource{}
			if r.ko.Spec.RuleGroup.RulesSource.RulesSourceList != nil {
				f5f2f0 := &svcsdktypes.RulesSourceList{}
				if r.ko.Spec.RuleGroup.RulesSource.RulesSourceList.GeneratedRulesType != nil {
					f5f2f0.GeneratedRulesType = svcsdktypes.GeneratedRulesType(*r.ko.Spec.RuleGroup.RulesSource.RulesSourceList.GeneratedRulesType)
				}
				if r.ko.Spec.RuleGroup.RulesSource.RulesSourceList.TargetTypes != nil {
					f5f2f0f1 := []svcsdktypes.TargetType{}
					for _, f5f2f0f1iter := range r.ko.Spec.RuleGroup.RulesSource.RulesSourceList.TargetTypes {
						var f5f2f0f1elem string
						f5f2f0f1elem = string(*f5f2f0f1iter)
						f5f2f0f1 = append(f5f2f0f1, svcsdktypes.TargetType(f5f2f0f1elem))
					}
					f5f2f0.TargetTypes = f5f2f0f1
				}
				if r.ko.Spec.RuleGroup.RulesSource.RulesSourceList.Targets != nil {
					f5f2f0.Targets = aws.ToStringSlice(r.ko.Spec.RuleGroup.RulesSource.RulesSourceList.Targets)
				}
				f5f2.RulesSourceList = f5f2f0
			}
			if r.ko.Spec.RuleGroup.RulesSource.RulesString != nil {
				f5f2.RulesString = r.ko.Spec.RuleGroup.RulesSource.RulesString
			}
			if r.ko.Spec.RuleGroup.RulesSource.StatefulRules != nil {
				f5f2f2 := []svcsdktypes.StatefulRule{}
				for _, f5f2f2iter := range r.ko.Spec.RuleGroup.RulesSource.StatefulRules {
					f5f2f2elem := &svcsdktypes.StatefulRule{}
					if f5f2f2iter.Action != nil {
						f5f2f2elem.Action = svcsdktypes.StatefulAction(*f5f2f2iter.Action)
					}
					if f5f2f2iter.Header != nil {
						f5f2f2elemf1 := &svcsdktypes.Header{}
						if f5f2f2iter.Header.Destination != nil {
							f5f2f2elemf1.Destination = f5f2f2iter.Header.Destination
						}
						if f5f2f2iter.Header.DestinationPort != nil {
							f5f2f2elemf1.DestinationPort = f5f2f2iter.Header.DestinationPort
						}
						if f5f2f2iter.Header.Direction != nil {
							f5f2f2elemf1.Direction = svcsdktypes.StatefulRuleDirection(*f5f2f2iter.Header.Direction)
						}
						if f5f2f2iter.Header.Protocol != nil {
							f5f2f2elemf1.Protocol = svcsdktypes.StatefulRuleProtocol(*f5f2f2iter.Header.Protocol)
						}
						if f5f2f2iter.Header.Source != nil {
							f5f2f2elemf1.Source = f5f2f2iter.Header.Source
						}
						if f5f2f2iter.Header.SourcePort != nil {
							f5f2f2elemf1.SourcePort = f5f2f2iter.Header.SourcePort
						}
						f5f2f2elem.Header = f5f2f2elemf1
					}
					if f5f2f2iter.RuleOptions != nil {
						f5f2f2elemf2 := []svcsdktypes.RuleOption{}
						for _, f5f2f2elemf2iter := range f5f2f2iter.RuleOptions {
							f5f2f2elemf2elem := &svcsdktypes.RuleOption{}
							if f5f2f2elemf2iter.Keyword != nil {
								f5f2f2elemf2elem.Keyword = f5f2f2elemf2iter.Keyword
							}
							if f5f2f2elemf2iter.Settings != nil {
								f5f2f2elemf2elem.Settings = aws.ToStringSlice(f5f2f2elemf2iter.Settings)
							}
							f5f2f2elemf2 = append(f5f2f2elemf2, *f5f2f2elemf2elem)
						}
						f5f2f2elem.RuleOptions = f5f2f2elemf2
					}
					f5f2f2 = append(f5f2f2, *f5f2f2elem)
				}
				f5f2.StatefulRules = f5f2f2
			}
			if r.ko.Spec.RuleGroup.RulesSource.StatelessRulesAndCustomActions != nil {
				f5f2f3 := &svcsdktypes.StatelessRulesAndCustomActions{}
				if r.ko.Spec.RuleGroup.RulesSource.StatelessRulesAndCustomActions.CustomActions != nil {
					f5f2f3f0 := []svcsdktypes.CustomAction{}
					for _, f5f2f3f0iter := range r.ko.Spec.RuleGroup.RulesSource.StatelessRulesAndCustomActions.CustomActions {
						f5f2f3f0elem := &svcsdktypes.CustomAction{}
						if f5f2f3f0iter.ActionDefinition != nil {
							f5f2f3f0elemf0 := &svcsdktypes.ActionDefinition{}
							if f5f2f3f0iter.ActionDefinition.PublishMetricAction != nil {
								f5f2f3f0elemf0f0 := &svcsdktypes.PublishMetricAction{}
								if f5f2f3f0iter.ActionDefinition.PublishMetricAction.Dimensions != nil {
									f5f2f3f0elemf0f0f0 := []svcsdktypes.Dimension{}
									for _, f5f2f3f0elemf0f0f0iter := range f5f2f3f0iter.ActionDefinition.PublishMetricAction.Dimensions {
										f5f2f3f0elemf0f0f0elem := &svcsdktypes.Dimension{}
										if f5f2f3f0elemf0f0f0iter.Value != nil {
											f5f2f3f0elemf0f0f0elem.Value = f5f2f3f0elemf0f0f0iter.Value
										}
										f5f2f3f0elemf0f0f0 = append(f5f2f3f0elemf0f0f0, *f5f2f3f0elemf0f0f0elem)
									}
									f5f2f3f0elemf0f0.Dimensions = f5f2f3f0elemf0f0f0
								}
								f5f2f3f0elemf0.PublishMetricAction = f5f2f3f0elemf0f0
							}
							f5f2f3f0elem.ActionDefinition = f5f2f3f0elemf0
						}
						if f5f2f3f0iter.ActionName != nil {
							f5f2f3f0elem.ActionName = f5f2f3f0iter.ActionName
						}
						f5f2f3f0 = append(f5f2f3f0, *f5f2f3f0elem)
					}
					f5f2f3.CustomActions = f5f2f3f0
				}
				if r.ko.Spec.RuleGroup.RulesSource.StatelessRulesAndCustomActions.StatelessRules != nil {
					f5f2f3f1 := []svcsdktypes.StatelessRule{}
					for _, f5f2f3f1iter := range r.ko.Spec.RuleGroup.RulesSource.StatelessRulesAndCustomActions.StatelessRules {
						f5f2f3f1elem := &svcsdktypes.StatelessRule{}
						if f5f2f3f1iter.Priority != nil {
							priorityCopy0 := *f5f2f3f1iter.Priority
							if priorityCopy0 > math.MaxInt32 || priorityCopy0 < math.MinInt32 {
								return nil, fmt.Errorf("error: field Priority is of type int32")
							}
							priorityCopy := int32(priorityCopy0)
							f5f2f3f1elem.Priority = &priorityCopy
						}
						if f5f2f3f1iter.RuleDefinition != nil {
							f5f2f3f1elemf1 := &svcsdktypes.RuleDefinition{}
							if f5f2f3f1iter.RuleDefinition.Actions != nil {
								f5f2f3f1elemf1.Actions = aws.ToStringSlice(f5f2f3f1iter.RuleDefinition.Actions)
							}
							if f5f2f3f1iter.RuleDefinition.MatchAttributes != nil {
								f5f2f3f1elemf1f1 := &svcsdktypes.MatchAttributes{}
								if f5f2f3f1iter.RuleDefinition.MatchAttributes.DestinationPorts != nil {
									f5f2f3f1elemf1f1f0 := []svcsdktypes.PortRange{}
									for _, f5f2f3f1elemf1f1f0iter := range f5f2f3f1iter.RuleDefinition.MatchAttributes.DestinationPorts {
										f5f2f3f1elemf1f1f0elem := &svcsdktypes.PortRange{}
										if f5f2f3f1elemf1f1f0iter.FromPort != nil {
											fromPortCopy0 := *f5f2f3f1elemf1f1f0iter.FromPort
											if fromPortCopy0 > math.MaxInt32 || fromPortCopy0 < math.MinInt32 {
												return nil, fmt.Errorf("error: field FromPort is of type int32")
											}
											fromPortCopy := int32(fromPortCopy0)
											f5f2f3f1elemf1f1f0elem.FromPort = fromPortCopy
										}
										if f5f2f3f1elemf1f1f0iter.ToPort != nil {
											toPortCopy0 := *f5f2f3f1elemf1f1f0iter.ToPort
											if toPortCopy0 > math.MaxInt32 || toPortCopy0 < math.MinInt32 {
												return nil, fmt.Errorf("error: field ToPort is of type int32")
											}
											toPortCopy := int32(toPortCopy0)
											f5f2f3f1elemf1f1f0elem.ToPort = toPortCopy
										}
										f5f2f3f1elemf1f1f0 = append(f5f2f3f1elemf1f1f0, *f5f2f3f1elemf1f1f0elem)
									}
									f5f2f3f1elemf1f1.DestinationPorts = f5f2f3f1elemf1f1f0
								}
								if f5f2f3f1iter.RuleDefinition.MatchAttributes.Destinations != nil {
									f5f2f3f1elemf1f1f1 := []svcsdktypes.Address{}
									for _, f5f2f3f1elemf1f1f1iter := range f5f2f3f1iter.RuleDefinition.MatchAttributes.Destinations {
										f5f2f3f1elemf1f1f1elem := &svcsdktypes.Address{}
										if f5f2f3f1elemf1f1f1iter.AddressDefinition != nil {
											f5f2f3f1elemf1f1f1elem.AddressDefinition = f5f2f3f1elemf1f1f1iter.AddressDefinition
										}
										f5f2f3f1elemf1f1f1 = append(f5f2f3f1elemf1f1f1, *f5f2f3f1elemf1f1f1elem)
									}
									f5f2f3f1elemf1f1.Destinations = f5f2f3f1elemf1f1f1
								}
								if f5f2f3f1iter.RuleDefinition.MatchAttributes.Protocols != nil {
									f5f2f3f1elemf1f1f2 := []int32{}
									for _, f5f2f3f1elemf1f1f2iter := range f5f2f3f1iter.RuleDefinition.MatchAttributes.Protocols {
										var f5f2f3f1elemf1f1f2elem int32
										protocolNumberCopy0 := *f5f2f3f1elemf1f1f2iter
										if protocolNumberCopy0 > math.MaxInt32 || protocolNumberCopy0 < math.MinInt32 {
											return nil, fmt.Errorf("error: field ProtocolNumber is of type int32")
										}
										protocolNumberCopy := int32(protocolNumberCopy0)
										f5f2f3f1elemf1f1f2elem = protocolNumberCopy
										f5f2f3f1elemf1f1f2 = append(f5f2f3f1elemf1f1f2, f5f2f3f1elemf1f1f2elem)
									}
									f5f2f3f1elemf1f1.Protocols = f5f2f3f1elemf1f1f2
								}
								if f5f2f3f1iter.RuleDefinition.MatchAttributes.SourcePorts != nil {
									f5f2f3f1elemf1f1f3 := []svcsdktypes.PortRange{}
									for _, f5f2f3f1elemf1f1f3iter := range f5f2f3f1iter.RuleDefinition.MatchAttributes.SourcePorts {
										f5f2f3f1elemf1f1f3elem := &svcsdktypes.PortRange{}
										if f5f2f3f1elemf1f1f3iter.FromPort != nil {
											fromPortCopy0 := *f5f2f3f1elemf1f1f3iter.FromPort
											if fromPortCopy0 > math.MaxInt32 || fromPortCopy0 < math.MinInt32 {
												return nil, fmt.Errorf("error: field FromPort is of type int32")
											}
											fromPortCopy := int32(fromPortCopy0)
											f5f2f3f1elemf1f1f3elem.FromPort = fromPortCopy
										}
										if f5f2f3f1elemf1f1f3iter.ToPort != nil {
											toPortCopy0 := *f5f2f3f1elemf1f1f3iter.ToPort
											if toPortCopy0 > math.MaxInt32 || toPortCopy0 < math.MinInt32 {
												return nil, fmt.Errorf("error: field ToPort is of type int32")
											}
											toPortCopy := int32(toPortCopy0)
											f5f2f3f1elemf1f1f3elem.ToPort = toPortCopy
										}
										f5f2f3f1elemf1f1f3 = append(f5f2f3f1elemf1f1f3, *f5f2f3f1elemf1f1f3elem)
									}
									f5f2f3f1elemf1f1.SourcePorts = f5f2f3f1elemf1f1f3
								}
								if f5f2f3f1iter.RuleDefinition.MatchAttributes.Sources != nil {
									f5f2f3f1elemf1f1f4 := []svcsdktypes.Address{}
									for _, f5f2f3f1elemf1f1f4iter := range f5f2f3f1iter.RuleDefinition.MatchAttributes.Sources {
										f5f2f3f1elemf1f1f4elem := &svcsdktypes.Address{}
										if f5f2f3f1elemf1f1f4iter.AddressDefinition != nil {
											f5f2f3f1elemf1f1f4elem.AddressDefinition = f5f2f3f1elemf1f1f4iter.AddressDefinition
										}
										f5f2f3f1elemf1f1f4 = append(f5f2f3f1elemf1f1f4, *f5f2f3f1elemf1f1f4elem)
									}
									f5f2f3f1elemf1f1.Sources = f5f2f3f1elemf1f1f4
								}
								if f5f2f3f1iter.RuleDefinition.MatchAttributes.TCPFlags != nil {
									f5f2f3f1elemf1f1f5 := []svcsdktypes.TCPFlagField{}
									for _, f5f2f3f1elemf1f1f5iter := range f5f2f3f1iter.RuleDefinition.MatchAttributes.TCPFlags {
										f5f2f3f1elemf1f1f5elem := &svcsdktypes.TCPFlagField{}
										if f5f2f3f1elemf1f1f5iter.Flags != nil {
											f5f2f3f1elemf1f1f5elemf0 := []svcsdktypes.TCPFlag{}
											for _, f5f2f3f1elemf1f1f5elemf0iter := range f5f2f3f1elemf1f1f5iter.Flags {
												var f5f2f3f1elemf1f1f5elemf0elem string
												f5f2f3f1elemf1f1f5elemf0elem = string(*f5f2f3f1elemf1f1f5elemf0iter)
												f5f2f3f1elemf1f1f5elemf0 = append(f5f2f3f1elemf1f1f5elemf0, svcsdktypes.TCPFlag(f5f2f3f1elemf1f1f5elemf0elem))
											}
											f5f2f3f1elemf1f1f5elem.Flags = f5f2f3f1elemf1f1f5elemf0
										}
										if f5f2f3f1elemf1f1f5iter.Masks != nil {
											f5f2f3f1elemf1f1f5elemf1 := []svcsdktypes.TCPFlag{}
											for _, f5f2f3f1elemf1f1f5elemf1iter := range f5f2f3f1elemf1f1f5iter.Masks {
												var f5f2f3f1elemf1f1f5elemf1elem string
												f5f2f3f1elemf1f1f5elemf1elem = string(*f5f2f3f1elemf1f1f5elemf1iter)
												f5f2f3f1elemf1f1f5elemf1 = append(f5f2f3f1elemf1f1f5elemf1, svcsdktypes.TCPFlag(f5f2f3f1elemf1f1f5elemf1elem))
											}
											f5f2f3f1elemf1f1f5elem.Masks = f5f2f3f1elemf1f1f5elemf1
										}
										f5f2f3f1elemf1f1f5 = append(f5f2f3f1elemf1f1f5, *f5f2f3f1elemf1f1f5elem)
									}
									f5f2f3f1elemf1f1.TCPFlags = f5f2f3f1elemf1f1f5
								}
								f5f2f3f1elemf1.MatchAttributes = f5f2f3f1elemf1f1
							}
							f5f2f3f1elem.RuleDefinition = f5f2f3f1elemf1
						}
						f5f2f3f1 = append(f5f2f3f1, *f5f2f3f1elem)
					}
					f5f2f3.StatelessRules = f5f2f3f1
				}
				f5f2.StatelessRulesAndCustomActions = f5f2f3
			}
			f5.RulesSource = f5f2
		}
		if r.ko.Spec.RuleGroup.StatefulRuleOptions != nil {
			f5f3 := &svcsdktypes.StatefulRuleOptions{}
			if r.ko.Spec.RuleGroup.StatefulRuleOptions.RuleOrder != nil {
				f5f3.RuleOrder = svcsdktypes.RuleOrder(*r.ko.Spec.RuleGroup.StatefulRuleOptions.RuleOrder)
			}
			f5.StatefulRuleOptions = f5f3
		}
		res.RuleGroup = f5
	}
	if r.ko.Spec.RuleGroupName != nil {
		res.RuleGroupName = r.ko.Spec.RuleGroupName
	}
	if r.ko.Spec.Rules != nil {
		res.Rules = r.ko.Spec.Rules
	}
	if r.ko.Spec.SourceMetadata != nil {
		f8 := &svcsdktypes.SourceMetadata{}
		if r.ko.Spec.SourceMetadata.SourceARN != nil {
			f8.SourceArn = r.ko.Spec.SourceMetadata.SourceARN
		}
		if r.ko.Spec.SourceMetadata.SourceUpdateToken != nil {
			f8.SourceUpdateToken = r.ko.Spec.SourceMetadata.SourceUpdateToken
		}
		res.SourceMetadata = f8
	}
	if r.ko.Spec.Tags != nil {
		f9 := []svcsdktypes.Tag{}
		for _, f9iter := range r.ko.Spec.Tags {
			f9elem := &svcsdktypes.Tag{}
			if f9iter.Key != nil {
				f9elem.Key = f9iter.Key
			}
			if f9iter.Value != nil {
				f9elem.Value = f9iter.Value
			}
			f9 = append(f9, *f9elem)
		}
		res.Tags = f9
	}
	if r.ko.Spec.Type != nil {
		res.Type = svcsdktypes.RuleGroupType(*r.ko.Spec.Type)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateRuleGroupOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateRuleGroup(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateRuleGroup", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.RuleGroupResponse != nil {
		f0 := &svcapitypes.RuleGroupResponse{}
		if resp.RuleGroupResponse.AnalysisResults != nil {
			f0f0 := []*svcapitypes.AnalysisResult{}
			for _, f0f0iter := range resp.RuleGroupResponse.AnalysisResults {
				f0f0elem := &svcapitypes.AnalysisResult{}
				if f0f0iter.AnalysisDetail != nil {
					f0f0elem.AnalysisDetail = f0f0iter.AnalysisDetail
				}
				if f0f0iter.IdentifiedRuleIds != nil {
					f0f0elem.IDentifiedRuleIDs = aws.StringSlice(f0f0iter.IdentifiedRuleIds)
				}
				if f0f0iter.IdentifiedType != "" {
					f0f0elem.IDentifiedType = aws.String(string(f0f0iter.IdentifiedType))
				}
				f0f0 = append(f0f0, f0f0elem)
			}
			f0.AnalysisResults = f0f0
		}
		if resp.RuleGroupResponse.Capacity != nil {
			capacityCopy := int64(*resp.RuleGroupResponse.Capacity)
			f0.Capacity = &capacityCopy
		}
		if resp.RuleGroupResponse.ConsumedCapacity != nil {
			consumedCapacityCopy := int64(*resp.RuleGroupResponse.ConsumedCapacity)
			f0.ConsumedCapacity = &consumedCapacityCopy
		}
		if resp.RuleGroupResponse.Description != nil {
			f0.Description = resp.RuleGroupResponse.Description
		}
		if resp.RuleGroupResponse.EncryptionConfiguration != nil {
			f0f4 := &svcapitypes.EncryptionConfiguration{}
			if resp.RuleGroupResponse.EncryptionConfiguration.KeyId != nil {
				f0f4.KeyID = resp.RuleGroupResponse.EncryptionConfiguration.KeyId
			}
			if resp.RuleGroupResponse.EncryptionConfiguration.Type != "" {
				f0f4.Type = aws.String(string(resp.RuleGroupResponse.EncryptionConfiguration.Type))
			}
			f0.EncryptionConfiguration = f0f4
		}
		if resp.RuleGroupResponse.LastModifiedTime != nil {
			f0.LastModifiedTime = &metav1.Time{*resp.RuleGroupResponse.LastModifiedTime}
		}
		if resp.RuleGroupResponse.NumberOfAssociations != nil {
			numberOfAssociationsCopy := int64(*resp.RuleGroupResponse.NumberOfAssociations)
			f0.NumberOfAssociations = &numberOfAssociationsCopy
		}
		if resp.RuleGroupResponse.RuleGroupArn != nil {
			f0.RuleGroupARN = resp.RuleGroupResponse.RuleGroupArn
		}
		if resp.RuleGroupResponse.RuleGroupId != nil {
			f0.RuleGroupID = resp.RuleGroupResponse.RuleGroupId
		}
		if resp.RuleGroupResponse.RuleGroupName != nil {
			f0.RuleGroupName = resp.RuleGroupResponse.RuleGroupName
		}
		if resp.RuleGroupResponse.RuleGroupStatus != "" {
			f0.RuleGroupStatus = aws.String(string(resp.RuleGroupResponse.RuleGroupStatus))
		}
		if resp.RuleGroupResponse.SnsTopic != nil {
			f0.SNSTopic = resp.RuleGroupResponse.SnsTopic
		}
		if resp.RuleGroupResponse.SourceMetadata != nil {
			f0f12 := &svcapitypes.SourceMetadata{}
			if resp.RuleGroupResponse.SourceMetadata.SourceArn != nil {
				f0f12.SourceARN = resp.RuleGroupResponse.SourceMetadata.SourceArn
			}
			if resp.RuleGroupResponse.SourceMetadata.SourceUpdateToken != nil {
				f0f12.SourceUpdateToken = resp.RuleGroupResponse.SourceMetadata.SourceUpdateToken
			}
			f0.SourceMetadata = f0f12
		}
		if resp.RuleGroupResponse.Tags != nil {
			f0f13 := []*svcapitypes.Tag{}
			for _, f0f13iter := range resp.RuleGroupResponse.Tags {
				f0f13elem := &svcapitypes.Tag{}
				if f0f13iter.Key != nil {
					f0f13elem.Key = f0f13iter.Key
				}
				if f0f13iter.Value != nil {
					f0f13elem.Value = f0f13iter.Value
				}
				f0f13 = append(f0f13, f0f13elem)
			}
			f0.Tags = f0f13
		}
		if resp.RuleGroupResponse.Type != "" {
			f0.Type = aws.String(string(resp.RuleGroupResponse.Type))
		}
		ko.Status.RuleGroupResponse = f0
	} else {
		ko.Status.RuleGroupResponse = nil
	}
	if resp.UpdateToken != nil {
		ko.Status.UpdateToken = resp.UpdateToken
	} else {
		ko.Status.UpdateToken = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateRuleGroupInput, error) {
	res := &svcsdk.UpdateRuleGroupInput{}

	if r.ko.Spec.AnalyzeRuleGroup != nil {
		res.AnalyzeRuleGroup = *r.ko.Spec.AnalyzeRuleGroup
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.DryRun != nil {
		res.DryRun = *r.ko.Spec.DryRun
	}
	if r.ko.Spec.EncryptionConfiguration != nil {
		f3 := &svcsdktypes.EncryptionConfiguration{}
		if r.ko.Spec.EncryptionConfiguration.KeyID != nil {
			f3.KeyId = r.ko.Spec.EncryptionConfiguration.KeyID
		}
		if r.ko.Spec.EncryptionConfiguration.Type != nil {
			f3.Type = svcsdktypes.EncryptionType(*r.ko.Spec.EncryptionConfiguration.Type)
		}
		res.EncryptionConfiguration = f3
	}
	if r.ko.Spec.RuleGroup != nil {
		f4 := &svcsdktypes.RuleGroup{}
		if r.ko.Spec.RuleGroup.ReferenceSets != nil {
			f4f0 := &svcsdktypes.ReferenceSets{}
			if r.ko.Spec.RuleGroup.ReferenceSets.IPSetReferences != nil {
				f4f0f0 := map[string]svcsdktypes.IPSetReference{}
				for f4f0f0key, f4f0f0valiter := range r.ko.Spec.RuleGroup.ReferenceSets.IPSetReferences {
					f4f0f0val := &svcsdktypes.IPSetReference{}
					if f4f0f0valiter.ReferenceARN != nil {
						f4f0f0val.ReferenceArn = f4f0f0valiter.ReferenceARN
					}
					f4f0f0[f4f0f0key] = *f4f0f0val
				}
				f4f0.IPSetReferences = f4f0f0
			}
			f4.ReferenceSets = f4f0
		}
		if r.ko.Spec.RuleGroup.RuleVariables != nil {
			f4f1 := &svcsdktypes.RuleVariables{}
			if r.ko.Spec.RuleGroup.RuleVariables.IPSets != nil {
				f4f1f0 := map[string]svcsdktypes.IPSet{}
				for f4f1f0key, f4f1f0valiter := range r.ko.Spec.RuleGroup.RuleVariables.IPSets {
					f4f1f0val := &svcsdktypes.IPSet{}
					if f4f1f0valiter.Definition != nil {
						f4f1f0val.Definition = aws.ToStringSlice(f4f1f0valiter.Definition)
					}
					f4f1f0[f4f1f0key] = *f4f1f0val
				}
				f4f1.IPSets = f4f1f0
			}
			if r.ko.Spec.RuleGroup.RuleVariables.PortSets != nil {
				f4f1f1 := map[string]svcsdktypes.PortSet{}
				for f4f1f1key, f4f1f1valiter := range r.ko.Spec.RuleGroup.RuleVariables.PortSets {
					f4f1f1val := &svcsdktypes.PortSet{}
					if f4f1f1valiter.Definition != nil {
						f4f1f1val.Definition = aws.ToStringSlice(f4f1f1valiter.Definition)
					}
					f4f1f1[f4f1f1key] = *f4f1f1val
				}
				f4f1.PortSets = f4f1f1
			}
			f4.RuleVariables = f4f1
		}
		if r.ko.Spec.RuleGroup.RulesSource != nil {
			f4f2 := &svcsdktypes.RulesSource{}
			if r.ko.Spec.RuleGroup.RulesSource.RulesSourceList != nil {
				f4f2f0 := &svcsdktypes.RulesSourceList{}
				if r.ko.Spec.RuleGroup.RulesSource.RulesSourceList.GeneratedRulesType != nil {
					f4f2f0.GeneratedRulesType = svcsdktypes.GeneratedRulesType(*r.ko.Spec.RuleGroup.RulesSource.RulesSourceList.GeneratedRulesType)
				}
				if r.ko.Spec.RuleGroup.RulesSource.RulesSourceList.TargetTypes != nil {
					f4f2f0f1 := []svcsdktypes.TargetType{}
					for _, f4f2f0f1iter := range r.ko.Spec.RuleGroup.RulesSource.RulesSourceList.TargetTypes {
						var f4f2f0f1elem string
						f4f2f0f1elem = string(*f4f2f0f1iter)
						f4f2f0f1 = append(f4f2f0f1, svcsdktypes.TargetType(f4f2f0f1elem))
					}
					f4f2f0.TargetTypes = f4f2f0f1
				}
				if r.ko.Spec.RuleGroup.RulesSource.RulesSourceList.Targets != nil {
					f4f2f0.Targets = aws.ToStringSlice(r.ko.Spec.RuleGroup.RulesSource.RulesSourceList.Targets)
				}
				f4f2.RulesSourceList = f4f2f0
			}
			if r.ko.Spec.RuleGroup.RulesSource.RulesString != nil {
				f4f2.RulesString = r.ko.Spec.RuleGroup.RulesSource.RulesString
			}
			if r.ko.Spec.RuleGroup.RulesSource.StatefulRules != nil {
				f4f2f2 := []svcsdktypes.StatefulRule{}
				for _, f4f2f2iter := range r.ko.Spec.RuleGroup.RulesSource.StatefulRules {
					f4f2f2elem := &svcsdktypes.StatefulRule{}
					if f4f2f2iter.Action != nil {
						f4f2f2elem.Action = svcsdktypes.StatefulAction(*f4f2f2iter.Action)
					}
					if f4f2f2iter.Header != nil {
						f4f2f2elemf1 := &svcsdktypes.Header{}
						if f4f2f2iter.Header.Destination != nil {
							f4f2f2elemf1.Destination = f4f2f2iter.Header.Destination
						}
						if f4f2f2iter.Header.DestinationPort != nil {
							f4f2f2elemf1.DestinationPort = f4f2f2iter.Header.DestinationPort
						}
						if f4f2f2iter.Header.Direction != nil {
							f4f2f2elemf1.Direction = svcsdktypes.StatefulRuleDirection(*f4f2f2iter.Header.Direction)
						}
						if f4f2f2iter.Header.Protocol != nil {
							f4f2f2elemf1.Protocol = svcsdktypes.StatefulRuleProtocol(*f4f2f2iter.Header.Protocol)
						}
						if f4f2f2iter.Header.Source != nil {
							f4f2f2elemf1.Source = f4f2f2iter.Header.Source
						}
						if f4f2f2iter.Header.SourcePort != nil {
							f4f2f2elemf1.SourcePort = f4f2f2iter.Header.SourcePort
						}
						f4f2f2elem.Header = f4f2f2elemf1
					}
					if f4f2f2iter.RuleOptions != nil {
						f4f2f2elemf2 := []svcsdktypes.RuleOption{}
						for _, f4f2f2elemf2iter := range f4f2f2iter.RuleOptions {
							f4f2f2elemf2elem := &svcsdktypes.RuleOption{}
							if f4f2f2elemf2iter.Keyword != nil {
								f4f2f2elemf2elem.Keyword = f4f2f2elemf2iter.Keyword
							}
							if f4f2f2elemf2iter.Settings != nil {
								f4f2f2elemf2elem.Settings = aws.ToStringSlice(f4f2f2elemf2iter.Settings)
							}
							f4f2f2elemf2 = append(f4f2f2elemf2, *f4f2f2elemf2elem)
						}
						f4f2f2elem.RuleOptions = f4f2f2elemf2
					}
					f4f2f2 = append(f4f2f2, *f4f2f2elem)
				}
				f4f2.StatefulRules = f4f2f2
			}
			if r.ko.Spec.RuleGroup.RulesSource.StatelessRulesAndCustomActions != nil {
				f4f2f3 := &svcsdktypes.StatelessRulesAndCustomActions{}
				if r.ko.Spec.RuleGroup.RulesSource.StatelessRulesAndCustomActions.CustomActions != nil {
					f4f2f3f0 := []svcsdktypes.CustomAction{}
					for _, f4f2f3f0iter := range r.ko.Spec.RuleGroup.RulesSource.StatelessRulesAndCustomActions.CustomActions {
						f4f2f3f0elem := &svcsdktypes.CustomAction{}
						if f4f2f3f0iter.ActionDefinition != nil {
							f4f2f3f0elemf0 := &svcsdktypes.ActionDefinition{}
							if f4f2f3f0iter.ActionDefinition.PublishMetricAction != nil {
								f4f2f3f0elemf0f0 := &svcsdktypes.PublishMetricAction{}
								if f4f2f3f0iter.ActionDefinition.PublishMetricAction.Dimensions != nil {
									f4f2f3f0elemf0f0f0 := []svcsdktypes.Dimension{}
									for _, f4f2f3f0elemf0f0f0iter := range f4f2f3f0iter.ActionDefinition.PublishMetricAction.Dimensions {
										f4f2f3f0elemf0f0f0elem := &svcsdktypes.Dimension{}
										if f4f2f3f0elemf0f0f0iter.Value != nil {
											f4f2f3f0elemf0f0f0elem.Value = f4f2f3f0elemf0f0f0iter.Value
										}
										f4f2f3f0elemf0f0f0 = append(f4f2f3f0elemf0f0f0, *f4f2f3f0elemf0f0f0elem)
									}
									f4f2f3f0elemf0f0.Dimensions = f4f2f3f0elemf0f0f0
								}
								f4f2f3f0elemf0.PublishMetricAction = f4f2f3f0elemf0f0
							}
							f4f2f3f0elem.ActionDefinition = f4f2f3f0elemf0
						}
						if f4f2f3f0iter.ActionName != nil {
							f4f2f3f0elem.ActionName = f4f2f3f0iter.ActionName
						}
						f4f2f3f0 = append(f4f2f3f0, *f4f2f3f0elem)
					}
					f4f2f3.CustomActions = f4f2f3f0
				}
				if r.ko.Spec.RuleGroup.RulesSource.StatelessRulesAndCustomActions.StatelessRules != nil {
					f4f2f3f1 := []svcsdktypes.StatelessRule{}
					for _, f4f2f3f1iter := range r.ko.Spec.RuleGroup.RulesSource.StatelessRulesAndCustomActions.StatelessRules {
						f4f2f3f1elem := &svcsdktypes.StatelessRule{}
						if f4f2f3f1iter.Priority != nil {
							priorityCopy0 := *f4f2f3f1iter.Priority
							if priorityCopy0 > math.MaxInt32 || priorityCopy0 < math.MinInt32 {
								return nil, fmt.Errorf("error: field Priority is of type int32")
							}
							priorityCopy := int32(priorityCopy0)
							f4f2f3f1elem.Priority = &priorityCopy
						}
						if f4f2f3f1iter.RuleDefinition != nil {
							f4f2f3f1elemf1 := &svcsdktypes.RuleDefinition{}
							if f4f2f3f1iter.RuleDefinition.Actions != nil {
								f4f2f3f1elemf1.Actions = aws.ToStringSlice(f4f2f3f1iter.RuleDefinition.Actions)
							}
							if f4f2f3f1iter.RuleDefinition.MatchAttributes != nil {
								f4f2f3f1elemf1f1 := &svcsdktypes.MatchAttributes{}
								if f4f2f3f1iter.RuleDefinition.MatchAttributes.DestinationPorts != nil {
									f4f2f3f1elemf1f1f0 := []svcsdktypes.PortRange{}
									for _, f4f2f3f1elemf1f1f0iter := range f4f2f3f1iter.RuleDefinition.MatchAttributes.DestinationPorts {
										f4f2f3f1elemf1f1f0elem := &svcsdktypes.PortRange{}
										if f4f2f3f1elemf1f1f0iter.FromPort != nil {
											fromPortCopy0 := *f4f2f3f1elemf1f1f0iter.FromPort
											if fromPortCopy0 > math.MaxInt32 || fromPortCopy0 < math.MinInt32 {
												return nil, fmt.Errorf("error: field FromPort is of type int32")
											}
											fromPortCopy := int32(fromPortCopy0)
											f4f2f3f1elemf1f1f0elem.FromPort = fromPortCopy
										}
										if f4f2f3f1elemf1f1f0iter.ToPort != nil {
											toPortCopy0 := *f4f2f3f1elemf1f1f0iter.ToPort
											if toPortCopy0 > math.MaxInt32 || toPortCopy0 < math.MinInt32 {
												return nil, fmt.Errorf("error: field ToPort is of type int32")
											}
											toPortCopy := int32(toPortCopy0)
											f4f2f3f1elemf1f1f0elem.ToPort = toPortCopy
										}
										f4f2f3f1elemf1f1f0 = append(f4f2f3f1elemf1f1f0, *f4f2f3f1elemf1f1f0elem)
									}
									f4f2f3f1elemf1f1.DestinationPorts = f4f2f3f1elemf1f1f0
								}
								if f4f2f3f1iter.RuleDefinition.MatchAttributes.Destinations != nil {
									f4f2f3f1elemf1f1f1 := []svcsdktypes.Address{}
									for _, f4f2f3f1elemf1f1f1iter := range f4f2f3f1iter.RuleDefinition.MatchAttributes.Destinations {
										f4f2f3f1elemf1f1f1elem := &svcsdktypes.Address{}
										if f4f2f3f1elemf1f1f1iter.AddressDefinition != nil {
											f4f2f3f1elemf1f1f1elem.AddressDefinition = f4f2f3f1elemf1f1f1iter.AddressDefinition
										}
										f4f2f3f1elemf1f1f1 = append(f4f2f3f1elemf1f1f1, *f4f2f3f1elemf1f1f1elem)
									}
									f4f2f3f1elemf1f1.Destinations = f4f2f3f1elemf1f1f1
								}
								if f4f2f3f1iter.RuleDefinition.MatchAttributes.Protocols != nil {
									f4f2f3f1elemf1f1f2 := []int32{}
									for _, f4f2f3f1elemf1f1f2iter := range f4f2f3f1iter.RuleDefinition.MatchAttributes.Protocols {
										var f4f2f3f1elemf1f1f2elem int32
										protocolNumberCopy0 := *f4f2f3f1elemf1f1f2iter
										if protocolNumberCopy0 > math.MaxInt32 || protocolNumberCopy0 < math.MinInt32 {
											return nil, fmt.Errorf("error: field ProtocolNumber is of type int32")
										}
										protocolNumberCopy := int32(protocolNumberCopy0)
										f4f2f3f1elemf1f1f2elem = protocolNumberCopy
										f4f2f3f1elemf1f1f2 = append(f4f2f3f1elemf1f1f2, f4f2f3f1elemf1f1f2elem)
									}
									f4f2f3f1elemf1f1.Protocols = f4f2f3f1elemf1f1f2
								}
								if f4f2f3f1iter.RuleDefinition.MatchAttributes.SourcePorts != nil {
									f4f2f3f1elemf1f1f3 := []svcsdktypes.PortRange{}
									for _, f4f2f3f1elemf1f1f3iter := range f4f2f3f1iter.RuleDefinition.MatchAttributes.SourcePorts {
										f4f2f3f1elemf1f1f3elem := &svcsdktypes.PortRange{}
										if f4f2f3f1elemf1f1f3iter.FromPort != nil {
											fromPortCopy0 := *f4f2f3f1elemf1f1f3iter.FromPort
											if fromPortCopy0 > math.MaxInt32 || fromPortCopy0 < math.MinInt32 {
												return nil, fmt.Errorf("error: field FromPort is of type int32")
											}
											fromPortCopy := int32(fromPortCopy0)
											f4f2f3f1elemf1f1f3elem.FromPort = fromPortCopy
										}
										if f4f2f3f1elemf1f1f3iter.ToPort != nil {
											toPortCopy0 := *f4f2f3f1elemf1f1f3iter.ToPort
											if toPortCopy0 > math.MaxInt32 || toPortCopy0 < math.MinInt32 {
												return nil, fmt.Errorf("error: field ToPort is of type int32")
											}
											toPortCopy := int32(toPortCopy0)
											f4f2f3f1elemf1f1f3elem.ToPort = toPortCopy
										}
										f4f2f3f1elemf1f1f3 = append(f4f2f3f1elemf1f1f3, *f4f2f3f1elemf1f1f3elem)
									}
									f4f2f3f1elemf1f1.SourcePorts = f4f2f3f1elemf1f1f3
								}
								if f4f2f3f1iter.RuleDefinition.MatchAttributes.Sources != nil {
									f4f2f3f1elemf1f1f4 := []svcsdktypes.Address{}
									for _, f4f2f3f1elemf1f1f4iter := range f4f2f3f1iter.RuleDefinition.MatchAttributes.Sources {
										f4f2f3f1elemf1f1f4elem := &svcsdktypes.Address{}
										if f4f2f3f1elemf1f1f4iter.AddressDefinition != nil {
											f4f2f3f1elemf1f1f4elem.AddressDefinition = f4f2f3f1elemf1f1f4iter.AddressDefinition
										}
										f4f2f3f1elemf1f1f4 = append(f4f2f3f1elemf1f1f4, *f4f2f3f1elemf1f1f4elem)
									}
									f4f2f3f1elemf1f1.Sources = f4f2f3f1elemf1f1f4
								}
								if f4f2f3f1iter.RuleDefinition.MatchAttributes.TCPFlags != nil {
									f4f2f3f1elemf1f1f5 := []svcsdktypes.TCPFlagField{}
									for _, f4f2f3f1elemf1f1f5iter := range f4f2f3f1iter.RuleDefinition.MatchAttributes.TCPFlags {
										f4f2f3f1elemf1f1f5elem := &svcsdktypes.TCPFlagField{}
										if f4f2f3f1elemf1f1f5iter.Flags != nil {
											f4f2f3f1elemf1f1f5elemf0 := []svcsdktypes.TCPFlag{}
											for _, f4f2f3f1elemf1f1f5elemf0iter := range f4f2f3f1elemf1f1f5iter.Flags {
												var f4f2f3f1elemf1f1f5elemf0elem string
												f4f2f3f1elemf1f1f5elemf0elem = string(*f4f2f3f1elemf1f1f5elemf0iter)
												f4f2f3f1elemf1f1f5elemf0 = append(f4f2f3f1elemf1f1f5elemf0, svcsdktypes.TCPFlag(f4f2f3f1elemf1f1f5elemf0elem))
											}
											f4f2f3f1elemf1f1f5elem.Flags = f4f2f3f1elemf1f1f5elemf0
										}
										if f4f2f3f1elemf1f1f5iter.Masks != nil {
											f4f2f3f1elemf1f1f5elemf1 := []svcsdktypes.TCPFlag{}
											for _, f4f2f3f1elemf1f1f5elemf1iter := range f4f2f3f1elemf1f1f5iter.Masks {
												var f4f2f3f1elemf1f1f5elemf1elem string
												f4f2f3f1elemf1f1f5elemf1elem = string(*f4f2f3f1elemf1f1f5elemf1iter)
												f4f2f3f1elemf1f1f5elemf1 = append(f4f2f3f1elemf1f1f5elemf1, svcsdktypes.TCPFlag(f4f2f3f1elemf1f1f5elemf1elem))
											}
											f4f2f3f1elemf1f1f5elem.Masks = f4f2f3f1elemf1f1f5elemf1
										}
										f4f2f3f1elemf1f1f5 = append(f4f2f3f1elemf1f1f5, *f4f2f3f1elemf1f1f5elem)
									}
									f4f2f3f1elemf1f1.TCPFlags = f4f2f3f1elemf1f1f5
								}
								f4f2f3f1elemf1.MatchAttributes = f4f2f3f1elemf1f1
							}
							f4f2f3f1elem.RuleDefinition = f4f2f3f1elemf1
						}
						f4f2f3f1 = append(f4f2f3f1, *f4f2f3f1elem)
					}
					f4f2f3.StatelessRules = f4f2f3f1
				}
				f4f2.StatelessRulesAndCustomActions = f4f2f3
			}
			f4.RulesSource = f4f2
		}
		if r.ko.Spec.RuleGroup.StatefulRuleOptions != nil {
			f4f3 := &svcsdktypes.StatefulRuleOptions{}
			if r.ko.Spec.RuleGroup.StatefulRuleOptions.RuleOrder != nil {
				f4f3.RuleOrder = svcsdktypes.RuleOrder(*r.ko.Spec.RuleGroup.StatefulRuleOptions.RuleOrder)
			}
			f4.StatefulRuleOptions = f4f3
		}
		res.RuleGroup = f4
	}
	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.RuleGroupArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}
	if r.ko.Spec.RuleGroupName != nil {
		res.RuleGroupName = r.ko.Spec.RuleGroupName
	}
	if r.ko.Spec.Rules != nil {
		res.Rules = r.ko.Spec.Rules
	}
	if r.ko.Spec.SourceMetadata != nil {
		f8 := &svcsdktypes.SourceMetadata{}
		if r.ko.Spec.SourceMetadata.SourceARN != nil {
			f8.SourceArn = r.ko.Spec.SourceMetadata.SourceARN
		}
		if r.ko.Spec.SourceMetadata.SourceUpdateToken != nil {
			f8.SourceUpdateToken = r.ko.Spec.SourceMetadata.SourceUpdateToken
		}
		res.SourceMetadata = f8
	}
	if r.ko.Spec.Type != nil {
		res.Type = svcsdktypes.RuleGroupType(*r.ko.Spec.Type)
	}
	if r.ko.Status.UpdateToken != nil {
		res.UpdateToken = r.ko.Status.UpdateToken
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteRuleGroupOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteRuleGroup(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteRuleGroup", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteRuleGroupInput, error) {
	res := &svcsdk.DeleteRuleGroupInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.RuleGroupArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}
	if r.ko.Spec.RuleGroupName != nil {
		res.RuleGroupName = r.ko.Spec.RuleGroupName
	}
	if r.ko.Spec.Type != nil {
		res.Type = svcsdktypes.RuleGroupType(*r.ko.Spec.Type)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.RuleGroup,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidRequestException":
		return true
	default:
		return false
	}
}
