// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type AttachmentStatus string

const (
	AttachmentStatus_CREATING AttachmentStatus = "CREATING"
	AttachmentStatus_DELETING AttachmentStatus = "DELETING"
	AttachmentStatus_ERROR    AttachmentStatus = "ERROR"
	AttachmentStatus_FAILED   AttachmentStatus = "FAILED"
	AttachmentStatus_READY    AttachmentStatus = "READY"
	AttachmentStatus_SCALING  AttachmentStatus = "SCALING"
)

type ConfigurationSyncState string

const (
	ConfigurationSyncState_CAPACITY_CONSTRAINED ConfigurationSyncState = "CAPACITY_CONSTRAINED"
	ConfigurationSyncState_IN_SYNC              ConfigurationSyncState = "IN_SYNC"
	ConfigurationSyncState_PENDING              ConfigurationSyncState = "PENDING"
)

type EncryptionType string

const (
	EncryptionType_AWS_OWNED_KMS_KEY EncryptionType = "AWS_OWNED_KMS_KEY"
	EncryptionType_CUSTOMER_KMS      EncryptionType = "CUSTOMER_KMS"
)

type FirewallStatusValue string

const (
	FirewallStatusValue_DELETING     FirewallStatusValue = "DELETING"
	FirewallStatusValue_PROVISIONING FirewallStatusValue = "PROVISIONING"
	FirewallStatusValue_READY        FirewallStatusValue = "READY"
)

type GeneratedRulesType string

const (
	GeneratedRulesType_ALLOWLIST GeneratedRulesType = "ALLOWLIST"
	GeneratedRulesType_DENYLIST  GeneratedRulesType = "DENYLIST"
)

type IDentifiedType string

const (
	IDentifiedType_STATELESS_RULE_CONTAINS_TCP_FLAGS        IDentifiedType = "STATELESS_RULE_CONTAINS_TCP_FLAGS"
	IDentifiedType_STATELESS_RULE_FORWARDING_ASYMMETRICALLY IDentifiedType = "STATELESS_RULE_FORWARDING_ASYMMETRICALLY"
)

type IPAddressType string

const (
	IPAddressType_DUALSTACK IPAddressType = "DUALSTACK"
	IPAddressType_IPV4      IPAddressType = "IPV4"
	IPAddressType_IPV6      IPAddressType = "IPV6"
)

type LogDestinationType string

const (
	LogDestinationType_CloudWatchLogs      LogDestinationType = "CloudWatchLogs"
	LogDestinationType_KinesisDataFirehose LogDestinationType = "KinesisDataFirehose"
	LogDestinationType_S3                  LogDestinationType = "S3"
)

type LogType string

const (
	LogType_ALERT LogType = "ALERT"
	LogType_FLOW  LogType = "FLOW"
	LogType_TLS   LogType = "TLS"
)

type OverrideAction string

const (
	OverrideAction_DROP_TO_ALERT OverrideAction = "DROP_TO_ALERT"
)

type PerObjectSyncStatus string

const (
	PerObjectSyncStatus_CAPACITY_CONSTRAINED PerObjectSyncStatus = "CAPACITY_CONSTRAINED"
	PerObjectSyncStatus_IN_SYNC              PerObjectSyncStatus = "IN_SYNC"
	PerObjectSyncStatus_PENDING              PerObjectSyncStatus = "PENDING"
)

type ResourceManagedStatus string

const (
	ResourceManagedStatus_ACCOUNT ResourceManagedStatus = "ACCOUNT"
	ResourceManagedStatus_MANAGED ResourceManagedStatus = "MANAGED"
)

type ResourceManagedType string

const (
	ResourceManagedType_AWS_MANAGED_DOMAIN_LISTS      ResourceManagedType = "AWS_MANAGED_DOMAIN_LISTS"
	ResourceManagedType_AWS_MANAGED_THREAT_SIGNATURES ResourceManagedType = "AWS_MANAGED_THREAT_SIGNATURES"
)

type ResourceStatus string

const (
	ResourceStatus_ACTIVE   ResourceStatus = "ACTIVE"
	ResourceStatus_DELETING ResourceStatus = "DELETING"
	ResourceStatus_ERROR    ResourceStatus = "ERROR"
)

type RevocationCheckAction string

const (
	RevocationCheckAction_DROP   RevocationCheckAction = "DROP"
	RevocationCheckAction_PASS   RevocationCheckAction = "PASS"
	RevocationCheckAction_REJECT RevocationCheckAction = "REJECT"
)

type RuleGroupType string

const (
	RuleGroupType_STATEFUL  RuleGroupType = "STATEFUL"
	RuleGroupType_STATELESS RuleGroupType = "STATELESS"
)

type RuleOrder string

const (
	RuleOrder_DEFAULT_ACTION_ORDER RuleOrder = "DEFAULT_ACTION_ORDER"
	RuleOrder_STRICT_ORDER         RuleOrder = "STRICT_ORDER"
)

type StatefulAction string

const (
	StatefulAction_ALERT  StatefulAction = "ALERT"
	StatefulAction_DROP   StatefulAction = "DROP"
	StatefulAction_PASS   StatefulAction = "PASS"
	StatefulAction_REJECT StatefulAction = "REJECT"
)

type StatefulRuleDirection string

const (
	StatefulRuleDirection_ANY     StatefulRuleDirection = "ANY"
	StatefulRuleDirection_FORWARD StatefulRuleDirection = "FORWARD"
)

type StatefulRuleProtocol string

const (
	StatefulRuleProtocol_DCERPC StatefulRuleProtocol = "DCERPC"
	StatefulRuleProtocol_DHCP   StatefulRuleProtocol = "DHCP"
	StatefulRuleProtocol_DNS    StatefulRuleProtocol = "DNS"
	StatefulRuleProtocol_FTP    StatefulRuleProtocol = "FTP"
	StatefulRuleProtocol_HTTP   StatefulRuleProtocol = "HTTP"
	StatefulRuleProtocol_ICMP   StatefulRuleProtocol = "ICMP"
	StatefulRuleProtocol_IKEV2  StatefulRuleProtocol = "IKEV2"
	StatefulRuleProtocol_IMAP   StatefulRuleProtocol = "IMAP"
	StatefulRuleProtocol_IP     StatefulRuleProtocol = "IP"
	StatefulRuleProtocol_KRB5   StatefulRuleProtocol = "KRB5"
	StatefulRuleProtocol_MSN    StatefulRuleProtocol = "MSN"
	StatefulRuleProtocol_NTP    StatefulRuleProtocol = "NTP"
	StatefulRuleProtocol_SMB    StatefulRuleProtocol = "SMB"
	StatefulRuleProtocol_SMTP   StatefulRuleProtocol = "SMTP"
	StatefulRuleProtocol_SSH    StatefulRuleProtocol = "SSH"
	StatefulRuleProtocol_TCP    StatefulRuleProtocol = "TCP"
	StatefulRuleProtocol_TFTP   StatefulRuleProtocol = "TFTP"
	StatefulRuleProtocol_TLS    StatefulRuleProtocol = "TLS"
	StatefulRuleProtocol_UDP    StatefulRuleProtocol = "UDP"
)

type StreamExceptionPolicy string

const (
	StreamExceptionPolicy_CONTINUE StreamExceptionPolicy = "CONTINUE"
	StreamExceptionPolicy_DROP     StreamExceptionPolicy = "DROP"
	StreamExceptionPolicy_REJECT   StreamExceptionPolicy = "REJECT"
)

type TCPFlag string

const (
	TCPFlag_ACK TCPFlag = "ACK"
	TCPFlag_CWR TCPFlag = "CWR"
	TCPFlag_ECE TCPFlag = "ECE"
	TCPFlag_FIN TCPFlag = "FIN"
	TCPFlag_PSH TCPFlag = "PSH"
	TCPFlag_RST TCPFlag = "RST"
	TCPFlag_SYN TCPFlag = "SYN"
	TCPFlag_URG TCPFlag = "URG"
)

type TargetType string

const (
	TargetType_HTTP_HOST TargetType = "HTTP_HOST"
	TargetType_TLS_SNI   TargetType = "TLS_SNI"
)
